### ISSUE TITLE
Deployment Issue on Netlify with NodeJS 20, Nuxt 3.10.3, and Pruvious 3.10.5

### ISSUE THREAD

**Issue by bauhem** [pruvious/pruvious#10]
### Description
I'm encountering a deployment issue on Netlify using Pruvious with the following setup:
- NodeJS Version: 20
- Nuxt Version: 3.10.3
- Pruvious Version: 3.10.5

### Steps to Reproduce
1. Setup a Nuxt project with Pruvious configured as per documentation.
2. Configure runtime environment variables for database connectivity and JWT secrets in `nuxt.config.ts` using `useRuntimeConfig`.
3. Deploy the project on Netlify with the build command `npm run build` and publish directory `dist`.

### Expected Behavior
The project deploys successfully on Netlify without errors, connecting to the Supabase PostgreSQL database and utilizing JWT secrets as configured.

### Actual Behavior
The deployment fails with an unhandled promise rejection error related to the `pg` package not being found, despite it being installed in the project dependencies. The error log is as follows:

`ERROR Unhandled Promise Rejection
{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Please install pg package manually","reason": ...}
`
### Additional Context
This setup works perfectly in a local development environment and on Vercel, but the issue arises specifically on Netlify.

## Issue Summary

- **Error Message**: "Please install pg package manually." This error indicates that Sequelize, the Node.js ORM used for PostgreSQL, requires the `pg` package to be installed in the environment where it's executing but was unable to find it.

- **Location of the Error**: The error originates from Sequelize's connection manager module. The process fails when trying to load the dialect module for PostgreSQL. This is highlighted by references to `sequelize/lib/dialects/abstract/connection-manager.js` and `sequelize/lib/dialects/postgres/connection-manager.js` in the stack trace.

- **Context of the Error**: This problem appears during the database connection setup phase by Sequelize. Setting up a connection to the database is a crucial early step in the application startup process, indicating that the `pg` package, which allows Sequelize to communicate with PostgreSQL databases, is not present or incorrectly configured in the project environment.

### Attempts to Fix
- Ensured that `pg` package is installed and listed in `package.json`.
- Tried requiring `pg` explicitly at the top of the Pruvious configuration file as suggested in some community posts.
- Checked Netlify environment variables and build settings.

### Request
Guidance on resolving this deployment issue or any potential workarounds to ensure successful deployment on Netlify.

Thank you for your assistance!

**Comment by murisceman** [comment]
Pruvious `v3.10.6` should fix this issue. Could you please try updating and verifying if it works with your setup? Thanks!

**Comment by bauhem** [comment]
Thanks, this is working.
