### ISSUE TITLE
Resolving correct page paths

### ISSUE THREAD

**Issue by sifferhans** [pruvious/pruvious#12]
Great work on Pruvious!

I am currently using it as my website CMS, and I want to have a "Recent articles" grid on the home page.
Each article card should have a href which should be correctly resolved, with an `articles` prefix and correct i18n prefix.

Is there a standard way to do this?

**Comment by murisceman** [comment]
Hey :)

There is no standard way at the moment, but it would make sense to create one. Let's say we send the language code in the query parameter `language` to a custom route, which looks like this:

```ts
import { joinRouteParts, resolveCollectionPathPrefix, prefixPrimaryLanguage , primaryLanguage, supportedLanguages  } from '#pruvious'
import { collections } from '#pruvious/collections'
import { query } from '#pruvious/server'

export default defineEventHandler(async (event) => {
  const qs = getQuery(event)

  // Let's resolve the language first
  const language = supportedLanguages.includes(qs.language) ? qs.language : primaryLanguage

  // Resolve language prefix in URL
  // Config: https://pruvious.com/docs/translations#configuration
  const languagePrefix = language === primaryLanguage && !prefixPrimaryLanguage ? '' : language

  // Resolve collection prefix in URL
  collectionPrefix = resolveCollectionPathPrefix(collections.articles, language, primaryLanguage)
  // ^ We could also just hard-code 'articles' in this case

  // Query articles (apply 'public' = true filter if needed)
  const recentArticles = query('articles').where('language', language).order('createdAt', 'desc').paginate(1, 9)
  // We can handle pagination with qs.page for example (just check if the value is a positive integer first)
  // ^ import { isPositiveInteger } from '#pruvious'
  // Caveat: qs.page will never be numeric, so we can import { numericSanitizer } from '#pruvious/server' as a helper

  // Resolve URL paths and return
  return recentArticles.map(({ path }) => ({
    path: joinRouteParts(languagePrefix, collectionPrefix, path)
  }))
})
```

Phew, a lot of code for something as simple as that. For now, you can use this approach, and I will add a utility for resolving URL paths for page-like collections in the next release (very soon). What are your thoughts?

_Disclaimer: The provided code might not work (haven't tested it)._

**Comment by sifferhans** [comment]
Awesome, thanks for the thorough answer! 🙌🏼

**Comment by sifferhans** [comment]
I do get an error when using your proposed solution:
```sh
[worker reload] [worker init] Cannot access 'articlesCollectionDefinition' before initialization
	at <anonymous> (.pruvious/server.ts:205:32)
	at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
	at async ModuleLoader.import (node:internal/modules/esm/loader:308:24)
	at async loadESM (node:internal/process/esm_loader:42:7)
	at async handleMainPromise (node:internal/modules/run_main:66:12)
```

**Comment by sifferhans** [comment]
I figured out the issue, and your solution worked 🥳

I moved the path resolving to a util function in `server/utils/path.ts`, which Nuxt probably registered before  `articleCollectionDefinition` was initialized.

**Comment by murisceman** [comment]
It can be tricky sometimes with auto imports from `#pruvious/server` or `#pruvious/collections`. You can always use `const { collections } = await import('#pruvious/collections')`, for example, in your function if this is the case, or place the function into a non-auto-imported directory.

**Comment by murisceman** [comment]
The release `v3.10.7` introduces two new utilities: `resolvePagePath` and `resolveLanguage`. More details can be found in the function comments at: https://github.com/pruvious/pruvious/blob/main/src/runtime/utils/server/pages.ts

I will be adding proper documentation pages to the website in the upcoming weeks.
