### ISSUE TITLE
S3 Storage broken on Tigris

### ISSUE THREAD

**Issue by smuriu** [pruvious/pruvious#15]
Thank you for your amazing work!

I have noticed an issue when using the S3 storage with a [Tigris](https://www.tigrisdata.com/) backend. Object keys are ending up stored with the preceding slash eg. `/filename.txt` vs `filename.txt` for an object at the root of the bucket. This makes the object accessible at `http://endpoint-url/bucket//filename.txt` instead of `http://endpoint-url/bucket/filename.txt`.

It seems other S3 backends (tested minio) ignore the forward slash in the key.

The forward slash comes from [joinRouteParts](https://github.com/pruvious/pruvious/blob/main/src/runtime/utils/string.ts#L188) util. ~This could be trimmed out on the util or~ calls to `s3PutObject` could explicitly trim out the forward slash.

Update: Seems to also affect CloudFlare [R2](https://developers.cloudflare.com/r2/).

**Comment by murisceman** [comment]
Thank you for using and reporting the issue!

I've fixed this in [fa5ef32e40395871a658cd8a5c7f22f2135ee376](https://github.com/pruvious/pruvious/commit/fa5ef32e40395871a658cd8a5c7f22f2135ee376) and will release a new version tomorrow.

**Comment by murisceman** [comment]
Released in [v3.10.8](https://github.com/pruvious/pruvious/releases/tag/v3.10.8)
