### ISSUE TITLE
Remove www.HOSTNAME from certbot command

### ISSUE THREAD

**Issue by leogenot** [pruvious/pruvious#16]
Hi I ran into an issue when setting the Certbot cetificates, it works when not setting the www. hostname and having only the first part of the command.

We are trying to host on a subdomain which can't work with the current implementation...

Would `npx pruvious sites add` be allowed to have an additional flag like `--no-www` that would omit Certbot www part?

Instead of running 
`sudo certbot certonly --non-interactive --nginx --agree-tos -m dev@email.com -d HOSTNAME -d www. HOSTNAME `
run
`sudo certbot certonly --non-interactive --nginx --agree-tos -m dev@email.com -d HOSTNAME `

**Comment by murisceman** [comment]
Hi! That makes sense. I'll provide the option to deploy without `www` in the upcoming releases next week.

**Comment by murisceman** [comment]
Added in [v3.10.8](https://github.com/pruvious/pruvious/releases/tag/v3.10.8) and updated [documentation](https://pruvious.com/docs/deployment#website-domain).
