### ISSUE TITLE
HMR: Lost styles after a change

### ISSUE THREAD

**Issue by DaniZGit** [pruvious/pruvious#18]
**Hello**
After making a change in collections by adding or removing a property, the styles do not load for dashboard pages after the HMR does its thing - as seen in the video below (sorry for the low brightness, idk what happeend there...):
https://github.com/pruvious/pruvious/assets/109877167/d4a39d70-d31e-40a4-9eda-321d0a84f0ed

It works normally after i reset the server.

OS: **WSL - Ubuntu**
Pruvious version: **3.10.7** (same thing happen on versions 3.10.6 and 3.10.8)
Nuxt version: **3.10.3**
I have theses modules installed: 
`modules: [
    "pruvious",
    "@nuxtjs/tailwindcss",
    "nuxt-primevue",
    "@nuxt/image",
    "nuxt-icon",
  ],`

**Comment by murisceman** [comment]
Hello! I have resolved the issue and will release an update once compatibility fixes for Nuxt `v3.11.0` are prepared.

**Comment by murisceman** [comment]
[Released!](https://github.com/pruvious/pruvious/releases/tag/v3.11.0)
