### ISSUE TITLE
Make use of NuxtImage?

### ISSUE THREAD

**Issue by smuriu** [pruvious/pruvious#19]
Hello,

This project includes the useful components `PruviousPicture` and `PruviousImage` as well as handling image optimization and resizing based on the parameters to the `image` field.

I wonder if the same features could be implemented using [NuxtImage](https://image.nuxt.com/)? This would take out image processing (and serving) logic from the CMS.

Additionally, apart from supporting a huge variety of providers, NuxtImage also includes a handy `useImage` composable that makes it easy to use optimized images beyond the `picture` or `img` tags; such as background images in CSS.

It is possible to use NuxtImage directly in the site frontend as is, but I think the developer experience is a little worse off in this case. What do you think?

**Comment by murisceman** [comment]
Hi,

Thank you for the suggestion. I have already considered Nuxt Image before adding image handling in Pruvious. I aimed to optimize from the API side, providing prepared URLs for defined image sizes when you `GET` a page. Components like `PruviousPicture` and `PruviousImage` generate HTML based on the image object received, without further optimizations unlike `NuxtPicture` and `NuxtImg`. I prefer managing breakpoints with the `media` attribute, hence my custom approach.

For backgrounds, you can use the `src` or `srcset` (array) props from the _image_ field in Pruvious and set it as a background in your component.

It might seem confusing which helper components to use initially. The rule is: if using the _image_ field in Pruvious, go for `PruviousPicture` or `PruviousImage`; for on-the-fly image optimization without storing data in the database, opt for Nuxt Image.

Cheers!

**Comment by murisceman** [comment]
I definitely need to catch up with the tutorial; I've procrastinated for too long. Also, I plan to publish more learning materials in the future, probably as an in-depth video course or something similar.
