### ISSUE TITLE
Hydration Issue on Dashboard Navigation

### ISSUE THREAD

**Issue by bauhem** [pruvious/pruvious#20]
## Description

When navigating between pages or sections in the CMS (e.g., going to the media section) without refreshing the page, the dashboard fails to display properly. This issue occurs in multiple environments: locally, on Netlify, and on Vercel. A hydration warning is visible in the local environment, indicating a potential issue with the rendering of Vue components.

## Steps to Reproduce

1. Navigate to dashboard
2. Attempt to navigate between different pages or sections within the CMS without refreshing the browser.

**Expected behavior:** The dashboard updates to display the new page or section content without needing a page refresh.

**Actual behavior:** The dashboard does not update properly, and a page refresh is required to view the new content.

## Workaround

It was found that the issue is related to Vue components not having a single root node, which leads to hydration errors when navigating between routes. Specifically, the error message received is:

[nuxt] /node_modules/pruvious/dist/runtime/components/dashboard/CollectionsOverview.vue does not have a single root node and will cause errors when navigating between routes.

**Solution:** Ensuring that each Vue component has a single root node by wrapping the content in a `div` tag directly inside the `template` tag resolves the issue. It's worth noting that tags other than `div` can be used as well, as long as there's a single root node.

**Example:**

- **No working:** This configuration leads to the hydration issue.
  ```html
  <template>
   <LazyPruviousMultiCollectionsOverview v-if="collection.mode === 'multi'" />
   <LazyPruviousSingleCollectionsOverview v-if="(collection as any).mode === 'single'" />
  </template>

-**Working:**
 ```html
<template>
  <div>
    <LazyPruviousMultiCollectionsOverview v-if="collection.mode === 'multi'" />
    <LazyPruviousSingleCollectionsOverview v-if="(collection as any).mode === 'single'" />
  </div>
</template>

**Comment by murisceman** [comment]
Fixed in [v3.11.1](https://github.com/pruvious/pruvious/releases/tag/v3.11.1).
