### ISSUE TITLE
Slider Field Type Causes Blank Page in Dashboard

### ISSUE THREAD

**Issue by DaniZGit** [pruvious/pruvious#34]
Hi,

In my collection I'm trying to use the [Slider](https://pruvious.com/docs/fields/slider) field type, this is my code:

```ts
import { defineCollection } from "#pruvious";

export default defineCollection({
  name: "categories",
  mode: "multi",
  translatable: true,
  fields: {
    title: {
      type: "text",
      options: {
        required: true,
      },
    },
    difficulty: {
      type: "slider",
      options: {
        required: true,
        max: 5,
        default: 3,
        marks: true,
        input: false,
      },
    },
  },
});
```

When I try to access the category within the dashboard (on url **/categories/4**), i get a blank screen and this error in the console log:
![image](https://github.com/pruvious/pruvious/assets/109877167/eabafa54-d530-40db-b1b8-92b7b25774bd)

The default value of the difficulty field is getting displayed correctly on the frontend tho (which is value 3). 

I'm using Pruvious version **3.11.7**

**Comment by murisceman** [comment]
Hey, this should be fixed now in `v3.11.8`.
