### ISSUE TITLE
Support configuring S3 path style

### ISSUE THREAD

**Issue by louisjrdev** [pruvious/pruvious#36]
I am using minio for S3 compatible storage, minio does not support the DNS style bucket.s3-server.com style access, it does however support the path based access. 

The S3 client is currently hardcoded to `forcePathStyle: false`, if this is made a config option, then pruvious can support S3 storage that uses either format. Allow setting it to `true` instead of just the current value `false`.

Without this, when I try to upload a file, I get `Invalid URL` error. I have tested this change my editing my node_modules/pruvious to have the `forcePathStyle: true` and I can now upload files to my minio storage server.

https://github.com/pruvious/pruvious/blob/5ae4c62f1433c7825ca2c574bc919194b15bb6dd/src/runtime/instances/s3.ts#L26C7-L26C29

**Comment by murisceman** [comment]
The `uploads.drive.forcePathStyle` option is now available in `v3.12.0`.
