### ISSUE TITLE
Allow javascript link in editor field

### ISSUE THREAD

**Issue by SuddenDev** [pruvious/pruvious#38]
Hi @murisceman!

My client asked why he can't add this `javascript:Cookiebot.show()` js snippet as a link inside the editor field. I unfortunately could not find a workaround to do it either (like switching from wysiwyg to the code view, since that is not supported atm as far as i can see).

Is this an oversight or a security reason that javascript snippets are not allowed / saved?

Thank you in advance!

**Comment by murisceman** [comment]
Hi @SuddenDev, this is a security measure that you can override in your block component. For example:

```vue
<template>
  <PruviousHTML :html="updatedText" />
</template>

<script lang="ts" setup>
import { editorField } from '#pruvious'

const props = defineProps({
  text: editorField(),
})

const updatedText = ref<string>()

watch(
  () => props.text,
  () => {
    updatedText.value = props.text?.replace(
      /<a href="showCookiebot">(.+?)<\/a>/g,
      `<button onclick="Cookiebot.show()">$1</button>`,
    )
  },
  { immediate: true },
)
</script>
```

The client should set the link in the _editor_ to `showCookiebot` for this to work. This approach can apply to any inline script, but it may introduce potential risks of XSS attacks, so it's better to implement it for specific scripts like this one.

**Comment by SuddenDev** [comment]
Thank you very much for the switft answer. I figured that just allowing JS would not be very safe. But the workaround is great! Thanks! ❤️
