### ISSUE TITLE
Possible deployment targets

### ISSUE THREAD

**Issue by StevenJPx2** [pruvious/pruvious#4]
# Problem
Hey there! Pruvious looks super cool, and I'll be using it for one of my clients.

In the [deployment page](https://pruvious.com/docs/deployment), it only mentions bare metal server and DO deployment. However, because it is Nuxt, can it not be edge-rendered or have the same deployment targets that Nitro has as well?

Will that mean that I can just deploy my Nuxt app the way I would normally deploy it and Pruvious will be served on `/dashboard`?

# Solution
If so, please update the documentation, or I can open a PR to do so! Thanks!

**Comment by murisceman** [comment]
Hello! That's great, I hope you enjoy it.

Regarding deployment, the Pruvious module has external dependencies (like [sharp](https://github.com/lovell/sharp)) that cannot be built with certain nitro presets like `cloudflare`, `vercel-edge`, etc. Unfortunately, I don't have a solution for this at the moment.

https://github.com/lovell/sharp/issues/3860

**Comment by StevenJPx2** [comment]
How about [IPX](https://github.com/unjs/ipx) made by the Nuxt team? It uses sharp and is completely compatible with Nitro. I think that they pre-render the images at build though, although I think that's static targets.

**Comment by murisceman** [comment]
https://github.com/nuxt/image/issues/1061

**Comment by StevenJPx2** [comment]
Okay thanks for the info!
