### ISSUE TITLE
Syntax highlighting in docs

### ISSUE THREAD

**Issue by andreasvirkus** [pruvious/pruvious#43]
Hi @murisceman, much love for creating & maintaining Pruvious! ❤️ 

Here's a small (and sorta vague) bug that I did not know how to work around for days and it was making the docs-browsing experience really bad from a legibility point.

By default, if my system theme gets picked up as dark theme, the Shiki theme remains as light. Once I click on the theme toggle in the header/nav, it corrects itself (this is the workaround I wasn't aware of at first).

![Screenshot 2024-07-30 at 10 23 13](https://github.com/user-attachments/assets/4edfadae-cf6c-4142-a41d-8df8aa42eaa4)
![Screenshot 2024-07-30 at 11 21 59](https://github.com/user-attachments/assets/8c2ddb74-67e2-48f7-b0ef-05a8fc51eb4c)

You can test it out with incognito, for example over at
https://pruvious.com/docs/blocks

**Comment by murisceman** [comment]
Hey @andreasvirkus, thanks for the kind words and reporting this bug! It's fixed now.
