### ISSUE TITLE
Docs typo in Translatable strings

### ISSUE THREAD

**Issue by andreasvirkus** [pruvious/pruvious#45]
Hi again, very minor but the `'All rights reserved'` and `'You are not logged in'` values are missing closing quotes for both EN and DE examples over at https://pruvious.com/docs/translations#translatable-strings

```diff
language: 'en',
strings: {
-  'All rights reserved': 'All rights reserved,
+  'All rights reserved': 'All rights reserved',
-  'You are not logged in': 'You are not logged in,
+  'You are not logged in': 'You are not logged in',
```

Side question - are the docs not open source?

**Comment by murisceman** [comment]
Fixed, thanks for reporting this.

The documentation is managed through Pruvious. While I considered creating it in Markdown, the desire to develop it using the CMS was stronger (:
