### ISSUE TITLE
How to approach multilingual collection tags

### ISSUE THREAD

**Issue by andreasvirkus** [pruvious/pruvious#46]
Say I've got a collection where a user can configure tags with the Chips field, like

```ts
export default defineCollection({
  name: 'events',
  mode: 'multi',
  translatable: true,
  fields: {
    tags: {
      type: 'chips',
      options: {
        choices: {
          marketing: 'Event marketing',
          promo: 'Promotion',
          conference: 'Conference',
          workshop: 'Workshop',
          social: 'Networking',
          festival: 'Festival',
        },
        required: true,
        placeholder: 'Select at least one category',
        visibleSuggestions: 2,
        sortable: true,
      },
    },
  },
})

```

How would I go about translating the tag values? They're used in the UI for filtering. 

If not currently possible, then as a workaround, should I just use the value as a translation key on the client side?

**Comment by murisceman** [comment]
The choice labels are already prepared as translatable strings under the `pruvious-dashboard` domain. See here:

https://github.com/pruvious/pruvious/blob/0035b6e74cde6a8967dc4f619d152ca350f28317/src/runtime/components/fields/ChipsField.vue#L12

The [`pruvious-dashboard`](https://github.com/pruvious/pruvious/blob/main/src/runtime/translatable-strings/standard/dashboard.en.ts) is a standard translation, but you can easily override it:

1. Disable the standard import in `nuxt.config.ts`.

https://github.com/pruvious/pruvious/blob/0035b6e74cde6a8967dc4f619d152ca350f28317/src/runtime/module-types.ts#L936-L955

2. Extend it in a custom `translatable-strings/pruvious-dashboard.en.ts` file:

```ts

import { defineTranslatableStrings } from '#pruvious'
import { standardTranslatableStringsDefinition } from '#pruvious/standard'

export default defineTranslatableStrings({
  ...standardTranslatableStringsDefinition.dashboard.en,
  strings: {
    ...standardTranslatableStringsDefinition.dashboard.en.strings,
    // ...
  },
})
```

**Comment by murisceman** [comment]
For the frontend (your website), it's best to use the choice values and map them to a custom translatable strings domain.
