### ISSUE TITLE
How to extend standard collections?

### ISSUE THREAD

**Issue by Michael201401** [pruvious/pruvious#50]
Hey,

first of all thank you very much for your great work. I am still in the evalution process, since I am new to the TS and Vue universe, but so far I like it and I very much like Pruvious.

**About my issue/question:**
I would like to extend the standard pages collection. I tried to replicate your solution from the "Merge translatable strings from Nuxt Layers" issue for this, but I get an error "Cannot register duplicate collection name pages [...]".

I added a file 'collections/pages.ts' in my project with the following content:

```
import { defineCollection } from '#pruvious'
import { pageLikeCollection, standardPagesCollectionDefinition } from '#pruvious/standard'

export default defineCollection(
    pageLikeCollection({
        ...standardPagesCollectionDefinition,
        additionalFields: {
            subtitle: {
                type: 'text',
                options: {
                    required: false
                }
            }
        },
        additionalPublicPagesFields: ['subtitle'],
    }),
)
```

**Comment by murisceman** [comment]
Hey, thank you for your kind words! I'm glad to hear that you're having a great experience so far.

Regarding your question, here's how you would do it:

```ts
import { defineCollection } from '#pruvious'
import { pageLikeCollection } from '#pruvious/standard'

export default defineCollection(
  pageLikeCollection({
    name: 'pages',
    additionalFields: {
      subtitle: {
        type: 'text',
        options: {},
      },
    },
    additionalPublicPagesFields: ['subtitle'],
  })
)
```

The `pageLikeCollection` helper outputs the standard `pages` collection definition by default (see [here](https://github.com/pruvious/pruvious/blob/main/src/runtime/collections/standard/pages.collection.ts)). You only need to add your new field there.

The final step is to disable the standard `pages` in the `nuxt.config.ts` file:

```ts
export default defineNuxtConfig({
  modules: ['pruvious'],
  pruvious: {
    standardCollections: {
      pages: false,
    }
  },
})
```

**Comment by Michael201401** [comment]
Thank you so much, also for your very quick answer. Your solution works as intended.
