### ISSUE TITLE
How to use collection in multi mode

### ISSUE THREAD

**Issue by v-moravec** [pruvious/pruvious#53]
Hello, I'm kinda lost. I tried to create 'news' collection, but I'm unable to get typed data.

I tried these two ways to do it:

```ts
import { getCollectionData } from "#pruvious/client"

const data = await getCollectionData("news")
```

And:
```ts
const data = await useFetch('/api/collections/news')
```

Both do return data, but I get no type inference.

getCollectionData:
```ts
const data: Pick<never, never>
```

useFetch:
```ts
const data: _AsyncData<any, FetchError<any> | null>
```

I can't find any way in docs how to get typed data from multi collection (single and pagelike collections work correctly). Am I supposed to use `query` method and create my own enpoints?

**Comment by murisceman** [comment]
Hello! Thank you for your input - I'll definitely need to improve the documentation about collection APIs.

The `getCollectionData` function retrieves data from a **public single-entry** collection (like site options, etc.), so this is likely not what you need, as `news` is a multi-entry collection.

By default, collection API routes are private and you must explicitly enable public access to them:

https://github.com/pruvious/pruvious/blob/8721a773121816090ff64451c2bba3f74954dba8/src/runtime/collections/collection.definition.ts#L428-L533

If you define your collection like this:

```ts
import { defineCollection } from '#pruvious'

export default defineCollection({
  name: 'news',
  mode: 'multi',
  apiRoutes: {
    readMany: 'public',
    read: 'public',
  },
  // ...
})
```

You can then fetch the data like this:

```ts
$fetch('/api/collections/news?language=en&order=createdAt:desc&perPage=10')
$fetch('/api/collections/news/1')
```

Keep in mind that this will also expose all collection fields and all possible filtering options via query string parameters. If you need to customize or limit this behavior, it's better to create your own API route, like `server/api/news.get.ts`, and use the [query builder](https://pruvious.com/docs/query-builder) to retrieve the collection data.

In general, there are many options and possibilities regarding collections and fields. I suggest reading about them directly in the code comments: https://github.com/pruvious/pruvious/blob/main/src/runtime/collections/collection.definition.ts

**Comment by murisceman** [comment]
Also, the `pageLikeCollection` helper (https://pruvious.com/docs/collections#page-like-collections) can create a collection with a public API route like `/api/pages/[slug]`. The standard `pages` collection uses this.

**Comment by v-moravec** [comment]
Oh, sorry, I forgot to mention I already did this:

```ts
import { defineCollection } from '#pruvious'

export default defineCollection({
  name: 'news',
  mode: 'multi',
  apiRoutes: {
    readMany: 'public',
    read: 'public',
  },
  // ...
})
```

The thing is this gives me back type `any`.

```ts
$fetch('/api/collections/news?language=en&order=createdAt:desc&perPage=10')
$fetch('/api/collections/news/1')
```

Can I at least specify the type with something like this (are there any auto generated types)?

```ts
$fetch<NewsPagedResult>('/api/collections/news')
```

**Comment by murisceman** [comment]
In that case, you can use the following:

```ts
import type { CastedFieldType, PaginateResult, PopulatedFieldType } from '#pruvious'

type CastedNewsRecord = CastedFieldType['news']
type PopulatedNewsRecord = PopulatedFieldType['news']
type NewsPagedResult = PaginateResult<CastedNewsRecord>
```

All generated types are available in the `index.ts` file located in the `.pruvious` directory of your project.

**Comment by v-moravec** [comment]
Great, that's exactly what I was looking for! Thank you. I would consider to make this more clear in the documentation - https://pruvious.com/docs/collections#multi-entry-collections - it would be nice to show the usage we discussed here.
