### ISSUE TITLE
globalThis.computedRef type errors

### ISSUE THREAD

**Issue by andreasvirkus** [pruvious/pruvious#57]
Sorry if this isn't Pruvious related, but I'm not getting the same TS errors in a vanilla Nuxt project:

Let's say I have a testimonials slider set up with the following logic

```js
// blocks/Testimonials.vue
const props = defineProps({
  title: textField({
    required: true,
  }),
  testimonials: repeaterField({
    required: true,
    subfields: {
      from: textSubfield(),
      company: textSubfield(),
      text: editorSubfield({
        required: true,
        toolbar: ['bold', 'italic', 'paragraph', 'link', 'bulletList'],
      }),
    },
  }),
})

const currentIndex = ref(0)
const currentTestimonial = computed(() => props.testimonials?.[currentIndex.value])
```

Now in my template, without importing anything extra from Vue, VSCode complains about the `currentTestimonial` and I'd have to sprinkle in excessive `.value` properties

![Screenshot 2024-09-14 at 14 56 38](https://github.com/user-attachments/assets/e5cd9413-5411-48d0-b2a1-b3a2d67ca807)

Yet if I add
```
import { computed } from 'vue'
```

![Screenshot 2024-09-14 at 14 56 48](https://github.com/user-attachments/assets/bf45925a-cd8c-4082-801e-c2f0f7070863)

**Comment by murisceman** [comment]
This may be an issue related to Volar. Does running the development server and/or reloading VSCode resolve it?

<img width="593" alt="image" src="https://github.com/user-attachments/assets/56f8d55b-acfd-43f7-94b9-c3acc0c77e0c">

**Comment by andreasvirkus** [comment]
Yeah, it did... Sorry 😅
