### ISSUE TITLE
Bug: 401 login error after fresh installation

### ISSUE THREAD

**Issue by SuddenDev** [pruvious/pruvious#59]
Hi @murisceman!

I'm currently setting up a new project for a client and after running `pnpm dlx pruvious@latest init <dir>`, everything starts fine. I go to the dashboard as usual, set my first user, then get a quick error flash and and a redirect to the login. Okay so i try logging in with the credentials I just set, but fro some reason I get a 401 error.

When I check the network tab, I see that the login itself is valid and I get a token back, but then redirecting to the profile page gives the 401 error. `(Unauthorized due to either invalid credentials or missing authentication)`

![image](https://github.com/user-attachments/assets/ab3d5202-f54d-41a4-ae35-f18cbc60389f)

I'm running on the latest nuxt version 3.13.2. Pruvious also gives the warning that the versions might not be compatible, but since the CLI tool set it up that way I figured it would be okay.

Any ideas why this is happening?

**Comment by murisceman** [comment]
Hi @SuddenDev!

It seems that the new version of `ofetch` (1.4.0), released three days ago, broke the Pruvious dashboard. Until I fix this, you can add `"ofetch": "1.3.4"` to your `package.json`.

**Comment by murisceman** [comment]
Fixed in `v3.13.0`.

**Comment by SuddenDev** [comment]
Wow, thanks for super quick fix! @murisceman
I'll try it out this afternoon!

**Comment by SuddenDev** [comment]
Works like a charm, thanks! ❤️
