### ISSUE TITLE
deployment-targets: enable vercel

### ISSUE THREAD

**Issue by crearis** [pruvious/pruvious#6]
Hi Muris,

this only is a question: i've read through #4 

At the moment for development-purposes I have pruvious successfully running on vercel for evaluation, for instance on this url:
https://demokratie.theaterpedia.org/

The only thing I needed to do, was to provide a postgres-database. Vercel provides even this for development purposes, it's easy to configure.

Do you think, I'll be having issues, because I've deployed to standard-targets?

Otherwise if you are interested:

1. that I test-out certain things with my vercel-deployment
2. that I document, how to deploy to vercel

I'll gladly assist you, just let me know :)

bye Hans

**Comment by crearis** [comment]
At the moment I am too busy to close this successfully, will come back to it later ...

**Comment by DiAvisoo** [comment]
> At the moment I am too busy to close this successfully, will come back to it later ...

I've been working for hours trying to get this deployed to vercel, so if you have some info on this it would be very much appreciated! :)
