### ISSUE TITLE
Persist sessions across deploys

### ISSUE THREAD

**Issue by andreasvirkus** [pruvious/pruvious#60]
Would there be a way to persist dashboard sessions across deploys? I've got Pruvious hosted on a ubuntu VM and running dockerized. With each deploy I do a simple docker compose down > up. That obviously restarts the Node process and all previous sessions are lost. But if someone is editing things in the Pruvious dashboard, they're no longer able to update things and would most likely try reloading the page (happened to a user), therefore losing their drafts.

Another weird experience is if the user has checked "Remember me" when logging in, but a deploy happens overnight and they return the next hour/day/... and need to log in again.

**Comment by murisceman** [comment]
Did you set up a [`jwt.secretKey`](https://pruvious.com/docs/authentication#module-options)? If not, Pruvious assigns a random key each time it starts, making the existing tokens invalid.

**Comment by andreasvirkus** [comment]
Sorry, even if I set the secret straight in my nuxt config, it still constantly logs out users 

```js
runtimeConfig: {
  NUXT_PRUVIOUS_JWT_SECRET_KEY: '...',
},
```
