### ISSUE TITLE
wrongly parsing block-imports in nested project / monorepo?

### ISSUE THREAD

**Issue by crearis** [pruvious/pruvious#7]
## Misbehaviour

In my monorepo from **apps/home/blocks/Hero.vue**
```
<script setup lang="ts">
import { SfButton } from '@crearis/vue'
import { defineBlock, imageField, linkField, textField } from '#pruvious'

defineBlock({ icon: 'Mouse' })

defineProps({
  image: imageField({
```

I am getting in **apps/home/.pruvious/blocks/Hero.vue**
```
// import { blockField, a-lot-of-imports } from '#pruvious'
import { SfButton } from '../..crearis/vue';   // < this is weird!!
export const __defineBlock = ({
  icon: 'Mouse'
});
export const __defineProps = ({
```

## Context
my package.json is correctly pointing to @crearis/vue. The monorepo is setup in a way that it should be accessible from .pruvious via @crearis/vue, should not be necessary to resolve it. If it should be resolved it could be ../../../../node_modules/@crearis/vue

**Comment by murisceman** [comment]
Fixed in https://github.com/pruvious/pruvious/commit/9d47a92ae70091e9c2eee3ad57ef79683f00902b

**Comment by crearis** [comment]
Thanks, I will test this tomorrow!

**Comment by crearis** [comment]
fix confirmend, thanks a lot!!
