### ISSUE TITLE
Improvement: unable to deselect image -> the upload does not exist

### ISSUE THREAD

**Issue by vanling** [pruvious/pruvious#75]
On the imageField, when file is removed you get "the upload does not exist"

<img width="371" alt="image" src="https://github.com/user-attachments/assets/9388af23-58ae-4b08-b3c9-e5354998fba8">

Nice to have: an "clear" or delete button, so you can select another image

**Comment by murisceman** [comment]
Thank you for reporting the bug. The fix will be included in the next release.
