### ISSUE TITLE
Idea:  PruviousPreset component for reusable layout elements

### ISSUE THREAD

**Issue by vanling** [pruvious/pruvious#76]
**Idea:** A component similar to `PruviousBlocks` that accepts a preset.

While building footers, I usually handle this via settings, as demonstrated in your example project. However, I don’t want to add a footer block to every page that I or clients create.

Wouldn’t it be nice to have something like this directly in the layout?

```jsx
<theHeader />
<slot />
<PruviousPreset id="1" name="footer" language="nl" />

<!-- Fetching `presetId` from a user-created settings page and the language via `getLanguage` -->
```

With this approach, you could create and edit footers using Pruvious’s flexibility, adding blocks to the footer as needed. _This might already be possible using `PruviousBlocks`, though it might require some additional data handling._

I can see more use cases for this feature, like managing a 404 page, header navigation, and mobile menus.

**Comment by murisceman** [comment]
Hey! This should be easily doable with `<PruviousBlocks />`. Here is an example (not tested):

```vue
<template>
  <div>
      <PruviousBlocks v-if="blocks" :blocks="blocks" />
  </div>
</template>

<script lang="ts" setup>
const blocks = await $fetch('/api/footer-blocks') // Query a preset and return its `blocks` property
</script>
```

Ideally, the block builder should be integrated as a standard field, allowing it to be used anywhere throughout the dashboard. This will probably be the case in Pruvious 4. Thank you for the idea! 💙

**Comment by vanling** [comment]
This worked! Awesome!

Had to load getPage once with a page to get the translations in layout(header/footer) 
_(this also made me realise i could make a /en/error-404 page, but its nice that this concept is possible)_

**error.vue**
```
// load a default page/language for the header/footer and translations in layout
await getPage('/en')

const {data} = useFetch<PresetResponse>('/api/preset?language=en&name=404')
const blocks = computed(() => data.value?.records[0].blocks || []);
```
