### ISSUE TITLE
Bug: You can only see the pages from default locale when adding a link in editorField

### ISSUE THREAD

**Issue by vanling** [pruvious/pruvious#77]
When trying to add a link to text in the editorField, the add link dropdown only shows the default locale.

<img width="1172" alt="image" src="https://github.com/user-attachments/assets/397cd784-6337-4afb-a06b-e6587401a34a">
_Editing english page with language `primary: 'nl'`_

**Comment by murisceman** [comment]
This is intended to work this way, but we could add a `languages` option to the `record` and `records` fields. It could be an array that accepts language codes or `'current'`. What do you think?

**Comment by murisceman** [comment]
When I think about it, this is actually a bug because all pages should be linkable throughout the site. I jumped to conclusions too quickly, focusing only on the `record` and `records` fields (though it would still be nice to have the `languages` option for them). Perhaps the `editor` doesn't need such an option at all, and the `Link.vue` component can be updated to include a language picker.

**Comment by vanling** [comment]
My guess was the intended behaviour was that the functionality should be the same for a linkfield 
<img width="418" alt="Screenshot 2024-11-07 at 08 08 37" src="https://github.com/user-attachments/assets/2cb27427-4948-40ba-9667-824b08a90e69">
which already works.

When adding a link in an editor field the "linkfield" misses the current language (i think)
<img width="668" alt="Screenshot 2024-11-07 at 08 09 16" src="https://github.com/user-attachments/assets/9c90da65-1e18-4a4c-881e-b04cd6009e11">
And this would be an bug than.

I would focus on the `selected` language of the 'add link' option in the editor. However, I agree that some users might want to add links in other languages. In that case, it would be a good improvement to add a dropdown for language selection. Fixing the `selected` language will still help by setting the default language effectively.

**Comment by murisceman** [comment]
Thanks for the additional context! I fixed this in `v3.13.3`.
