### ISSUE TITLE
Uploaded images not accessible on build

### ISSUE THREAD

**Issue by urbgimtam** [pruvious/pruvious#8]
Hi and congratulations for this amazing cms, it looks and feels amazing!

I'm following the tutorial, and when I upload an image during development, everything works perfectly. Images are correctly rendered both on the "dashboard" as well as on the "front."

In VSCode, I can see the images being copied to "/public/uploads", and they're visible.

However, after performing a regular nuxt build (npm run build && node .output/server/index.mjs), all images fail to be rendered on the browser, with "404 - not found". On build, they are not being copied/transformed onto '/public/uploads'

On nuxt.config.ts, I have these settings specified: 
```
pruvious: {
    uploads: {
      maxFileSize: '512 MB',
      drive: {
        type: 'local',
        path: './.uploads',
        urlPrefix: 'uploads',
      },
    },
```

but even without them, it behaves the same. 

I may be doing something incredibly wrong, but can't seem to "get it".

**Comment by murisceman** [comment]
Hi there, and thank you! I'm glad you enjoy it.

The uploads are fully detached from Nuxt after building the project, and the idea is to serve the `.uploads` folder directly from Nginx, Apache, etc. There is an example of a manual Nginx configuration on this documentation page: https://pruvious.com/docs/deployment#manual-deployment

```nginx
server {
  location /uploads {
    alias /srv/example.com/.uploads;
  }
}
```

**Comment by murisceman** [comment]
Yeah, unfortunately dynamic content cannot be added to .`output/public` after building the project. Reference: https://github.com/nuxt/nuxt/issues/15779#issuecomment-1397418353

The easiest solution to make it work locally is by using a custom `hosts` entry and adding the rewrite in Nginx. Other solutions, such as creating a symlink in `public`, have drawbacks and only the files existing before the build will be served.

**Comment by murisceman** [comment]
Also, if you you take a look in `.output/server/chunks/nitro/node-server.mjs`, you'll notice the `assets` const where all contents from the `public` folder are listed.

**Comment by urbgimtam** [comment]
Thank you so much for your help and explanation. Now I understand.

Thank you and keep up the good work.

**Comment by AnoRebel** [comment]
Sorry for adding up to this, I didn't want to open a new issue.
I just realized this issue as I was trying to host this and almost opened a new issue.
Any pointers on how I would go about doing this in IIS?
