### ISSUE TITLE
Add pruvious to existing nuxt project with pages

### ISSUE THREAD

**Issue by AnoRebel** [pruvious/pruvious#84]
Hi again,
I have an existing Nuxt website which uses the 'pages' directory i.e file routing. I'm trying to implement blog/news feature using pruvious. I've setup the collection, but when i get to the dashboard for add blogs/news, I get my error page saying no such file or directory for the blog/news page on both the preview and on opening on the new tab too.
```sh
ENOENT: no such file or directory, open '/pages/news/[...slug].vue'
```
I figured it's because I'm using file routing.
So is there a way to do this or am I missing something?

**Comment by murisceman** [comment]
Hi! You can try changing the `pruvious.api.routes['pages.get']` option in in your `nuxt.config.ts`. See here: https://github.com/pruvious/pruvious/blob/b58d71b5512d0e4f4c28de09acbc06645b84db7b/src/runtime/module-types.ts#L117-L125

**Comment by murisceman** [comment]
Hi! Could you provide more information about the files in the `pages` directory? If this is an existing Nuxt project, you need to include a catch-all page with the `<PruviousPage />` component, like this: https://github.com/pruvious/pruvious/blob/main/src/runtime/pages/%5B...slug%5D.vue

**Comment by AnoRebel** [comment]
> Hi! You can try changing the `pruvious.api.routes['pages.get']` option in in your `nuxt.config.ts`.

What should I change it to? I tried setting it to false but nothing changed.



> Hi! Could you provide more information about the files in the `pages` directory? If this is an existing Nuxt project, you need to include a catch-all page with the `<PruviousPage />` component, like this: [`main`/src/runtime/pages/%5B...slug%5D.vue](https://github.com/pruvious/pruvious/blob/main/src/runtime/pages/%5B...slug%5D.vue?rgh-link-date=2024-12-10T16%3A01%3A16Z)

What specific information do you need?
```sh
pages
├── about-us
│   ├── foundation.vue
│   ├── index.vue
│   ├── labworks.vue
├── index.vue
├── privacy-policy.vue
├── production.vue
├── products.vue
├── [...slug].vue
└── trainings.vue
```

This is how my pages directory looks like.
I added the `[...slug].vue` catch all route but i still get the same nuxt error page for route not found.

This is my news collection:
```ts
import { defineCollection } from "#pruvious";
import { pageLikeCollection } from "#pruvious/standard";

// @see https://pruvious.com/docs/collections
export default defineCollection(
  pageLikeCollection({
    name: "news",
    pathPrefix: "news",
    icon: "Pin",
    allowedLayouts: ["news"],
    additionalPublicPagesFields: ["headline", "author", "tags"],
    additionalFields: {
      headline: {
        type: "text",
        options: {
          label: "Headline",
          description: "If left empty, the page title will be used",
        },
      },
      tags: {
        type: "chips",
        options: {
          choices: {
            ktl: "KTL",
            hts: "HTS",
            charity: "Charity Works",
            httc: "HTTC",
            donation: "Donations",
          },
          required: false,
          label: "Tags",
          sortable: true,
          description: "Category tags for the news",
        },
      },
      author: {
        type: "record",
        options: {
          collection: "users",
          fields: ["firstName"],
          populate: true,
        },
      },
    },
  })
);
```

**Comment by murisceman** [comment]
> What should I change it to? I tried setting it to false but nothing changed.

I misread your question initially, so I quickly deleted my first answer, hoping you wouldn't see it. Please ignore this, as it relates to `/api/pages`.

> What specific information do you need?

Actually, the error `ENOENT: no such file or directory, open '/pages/news/[...slug].vue'` indicates that something is trying to access the `pages` folder from your top-level directory. Does the same thing happen if you disable Pruvious and open `http://localhost:3000/news/foo`?

**Comment by AnoRebel** [comment]
So, that error doesn't seem to always occur. The preview pane shows 500 error but when i manually navigate to something like `news/foo` i get a 404 even without removing pruvious from `nuxt.config`.

**Comment by murisceman** [comment]
This is hard to guess without a reproduction. If you’d like, you can invite me to your repository and I can take a look.

**Comment by AnoRebel** [comment]
Well, its inside my company repo, but I will try to see if I can give you access.

Funny thing, when I create a page using the pages tab in the dashboard with example `news/pages`, it works fine, so is the `news` prefix the problem?
I would use this method, since I'm on a tight schedule, but the drawback is that I don't think I'll be able to access the `news` index page with the listing of all the news articles.

**Comment by AnoRebel** [comment]
I was finally able to fix the error. Apparently it was a vite error caused by a typo in a component I was using ‍🤦‍♂️
Apologies for this and thank you for the help.
