### ISSUE TITLE
Cannot start nuxt:  relative srcpath does not exist

### ISSUE THREAD

**Issue by AnoRebel** [pruvious/pruvious#88]
Hi again,
So after the update today, I found this bug. It happens when you set a custom path for the uploads in the file management section:
```ts
pruvious: {
    uploads: {
      drive: {
        type: 'local',
        path: './.uploads',
        urlPrefix: 'uploads',
      },
    },
}
```
But if I set an absolute path, it runs fine, e.g:
```ts
pruvious: {
    uploads: {
      drive: {
        type: 'local',
        path: '/.uploads',
        urlPrefix: 'uploads',
      },
    },
}
```
I'm calling it a bug but I'm not sure if it is, if it's not, would be nice to update the example in the website or an alternative to pass a relative path.

**Comment by murisceman** [comment]
Hi! I just tested this, and it works on my end. The `pruvious.uploads.drive.path` is relative to your current working directory (`process.cwd()`). Do you use a monorepo? If you can confirm that `cwd` matches your project folder, could you let me know which operating system and versions of Node.js, Nuxt, and Pruvious you are using?

**Comment by AnoRebel** [comment]
This is the exact error I get:
```sh
 ERROR  Cannot start nuxt:  relative srcpath does not exist                                                                              10:54:54 PM

  at symlinkPathsSync (node_modules/fs-extra/lib/ensure/symlink-paths.js:91:25)
  at Object.createSymlinkSync (node_modules/fs-extra/lib/ensure/symlink.js:54:20)
  at setup (node_modules/pruvious/dist/module.mjs:454:12)
  at normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2140:37)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2397:95)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:4684:5)
  at async NuxtDevServer._load (node_modules/nuxi/dist/chunks/dev2.mjs:1894:5)
  at async NuxtDevServer.load (node_modules/nuxi/dist/chunks/dev2.mjs:1828:7)
  at async NuxtDevServer.init (node_modules/nuxi/dist/chunks/dev2.mjs:1823:5)
  at async Object.run (node_modules/nuxi/dist/chunks/dev-child.mjs:104:5)
```

And after more testing I found even passing an absolute path still gives the same error, the only solution that seems to work so far is not passing the `path` option completely i.e:
```ts
pruvious: {
    uploads: {
      drive: {
        type: 'local',
        // path: '/.uploads',
        urlPrefix: 'uploads',
      },
    },
}
```

**Comment by murisceman** [comment]
This error is thrown here: https://github.com/jprichardson/node-fs-extra/blob/d96f2655f181f1c6b1641711619400140a89d027/lib/ensure/symlink-paths.js#L91

The code that calls `ensureSymlinkSync` is located here: https://github.com/pruvious/pruvious/blob/16ccf12d6e7f45e1260f8121db0295c9a2c73833/src/module.ts#L549

Can you try manually creating the `.uploads` folder in your project and then starting the dev server?

**Comment by murisceman** [comment]
The `.uploads` folder is indeed a symlink to `public/uploads`. Which specific `pruvious.uploads.drive.path` are you trying to use?

**Comment by AnoRebel** [comment]
Okay, I think I've pinpointed the issue, it seems passing the `urlPrefix` as an empty string is the cause of the problem ‍🤦‍♂️

**Comment by AnoRebel** [comment]
I think I've kinda figured it out, the `path` works fine, but when working with the `urlPrefix` is when I messed things up. I noticed changing the `urlPrefix` creates a symlinked directory to the directory name passed in `path`, so when I passed an empty `urlPrefix`, it symlinked to my global `public` directory, which in turn deleted it when I changed/removed the values and it's also probably why I get the crashing error because I'm messing with the nuxt `public` folder 🤔

**Comment by murisceman** [comment]
That makes sense now. The `urlPrefix` cannot be an empty string, and a symlink cannot reference itself. In Pruvious v4, the `urlPrefix` limitation will be removed since file uploads are no longer served through the `public` directory.

**Comment by AnoRebel** [comment]
Awesome.
Thanks for the help in debugging. Would be nice to add that disclaimer in the docs, for people like me who try to leverage the public folder.

Quick question, if the uploads wont be served from the `public` directory wont it affect any assets/media added in during runtime?

**Comment by murisceman** [comment]
Thanks for pointing this out. I've updated the `urlPrefix` comment in the code.

> Quick question, if the uploads wont be served from the`public` directory wont it affect any assets/media added in during runtime?

It won't, because the uploads will be streamed through a Nitro server handler. This implementation will be slightly slower than the current approach, where files are served statically, but it enables upload functionality in Cloudflare Workers, Netlify, Vercel, etc.

**Comment by AnoRebel** [comment]
This sounds awesome. Great work! 

Also, will the v4 fix the sqlite issue?

**Comment by murisceman** [comment]
> Also, will the v4 fix the sqlite issue?

Yes, I used `better-sqlite3` this time.
