### ISSUE TITLE
Dev server stuck after making some changes

### ISSUE THREAD

**Issue by IllMind11** [pruvious/pruvious#9]
I just added a collection, but my dev server is not responding, I checked the networks tab and it's stuck on profile request.

Build is working fine.

I'm on Linux x64.

**Comment by murisceman** [comment]
Do you use `nuxt dev` to start your development server? If yes, I suggest changing the command to `previous dev`, which resolves the issue (related to `node-sqlite3` and worker threads) by catching the error and restarting the server.

**Comment by IllMind11** [comment]
I found the issue: I was using node v18, switched to v20, problem got fixed.
